actual:

  login:
    method: "openid"
    openid:
      enforce: true
      providerName: "Authentik"
      discoveryUrl: "https://authentik.framsburg.ch/application/o/actual/.well-known/openid-configuration"
      tokenExpiration: 3600
      existingSecret:
        name: "actualbudget-openid-secret"
        clientIdKey: "clientId"
        clientSecretKey: "clientSecret"

  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: 'actual.framsburg.ch'
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts: ['actual.framsburg.ch']
        secretName: 'actual-framsburg-ch-tls'

  persistence:
    enabled: true
