actual:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
    hosts:
      - host: 'actual.framsburg.ch'
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts: ['actual.framsburg.ch']
        secretName: 'actual-framsburg-ch-tls'

  persistence:
    enabled: true
